version: '3'

services:
  todoshare-server:
    build: .
    container_name: todoshare
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todosharedb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend
  db:
    image: postgres
    network_mode: bridge
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=testuser
      - POSTGRES_DB=todosharedb
    restart: always

volumes:
  postgres-data:

networks:
  backend: